# Generated by Django 6.0 on 2025-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('alumni', 'Alumni'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('student', 'Student')], max_length=10)),
                ('department', models.CharField(choices=[('chem', 'Chemistry'), ('ma', 'Mathematics'), ('ee', 'Electrical Engineering'), ('bt', 'Biotechnology'), ('ba', 'Business Administration'), ('ce', 'Civil Engineering'), ('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering'), ('phy', 'Physics'), ('me', 'Mechanical Engineering')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
