# Generated by Django 6.0 on 2025-12-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('ee', 'Electrical Engineering'), ('bt', 'Biotechnology'), ('ba', 'Business Administration'), ('ma', 'Mathematics'), ('phy', 'Physics'), ('chem', 'Chemistry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff'), ('student', 'Student'), ('alumni', 'Alumni')], max_length=10),
        ),
    ]
